name: ingest
channels:
  - powerai
  - conda-forge
  - defaults
dependencies:
  - cx_oracle=7.2
  - ipykernel
  - pandas=1.0
  - python=3.7
  - python-dotenv=0.13
  - tqdm=4.46
  - ipywidgets=7.5
  - pyarrow=0.16.0
  - logzero==1.5.0
