name: bsql
channels:
  - blazingsql/label/cuda10.2
  - blazingsql
  - rapidsai
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - blazingsql=0.15
  - cugraph=0.15
  - ipykernel
  - logzero=1.5
  - openjdk=8
  - orjson=3.3
  - python-arango=5.4
  - python-dotenv=0.14
  - python=3.7
  - xlsxwriter=1.3
  - matplotlib=3.3
  